apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  
  selector:
    name: rs-nginx
    type: rs-front-end
    