apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  
  selector:
    name: rs-nginx
    type: rs-front-end
    